# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Uomi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Uomi
pod 'Firebase/Core'
pod 'FirebaseAuth'
pod 'FirebaseDatabase'
#pod 'TesseractOCRiOS', '~> 4.0'
#pod 'BraintreeDropIn'
pod 'McPicker'

end
